### ISSUE TITLE
wheel test doesn't work

### ISSUE THREAD

**Issue by ask-compu** [berarma/oversteer#107]
on the first test after pressing a button on the wheel to begin the test nothing happens and the terminal shows this
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/oversteer/test.py", line 129, in test1
    left_effect = self.create_left_effect(0)
  File "/usr/lib/python3.6/site-packages/oversteer/test.py", line 67, in create_left_effect
    left_effect.id = self.input_device.upload_effect(left_effect)
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 309, in upload_effect
    data = bytes(buffer(effect)[:])
```

Ubuntu 18.04
Logitech G29 with new-lg4ff

**Comment by berarma** [comment]
Sorry, I forgot about this. Could you try again? It looks like there's some error lines missing.

**Comment by ask-compu** [comment]
tried it again after updating oversteer (clone, build, and install again) and got
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/oversteer/test.py", line 129, in test1
    left_effect = self.create_left_effect(0)
  File "/usr/lib/python3.6/site-packages/oversteer/test.py", line 67, in create_left_effect
    left_effect.id = self.input_device.upload_effect(left_effect)
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 309, in upload_effect
    data = bytes(buffer(effect)[:])
NameError: name 'buffer' is not defined
```

**Comment by berarma** [comment]
I guess it's some incompatibility between python libs and glibc as can be deduced from the following post: https://itch.io/post/1095186

Can you try the same solution that worked for that user?

**Comment by ask-compu** [comment]
no it's fine, i'll be building a new computer some time soon anyways and putting Kubuntu 22.04 on it

**Comment by berarma** [comment]
Ok, I'll close this.

**Comment by ask-compu** [comment]
test works on the new PC
