### ISSUE TITLE
Oversteer won't launch on Fedora 36

### ISSUE THREAD

**Issue by Midnight64** [berarma/oversteer#109]
Every time i try to open Oversteer on the terminal i get this:

Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 53, in <module>
    sys.exit(app.run(sys.argv))
  File "/usr/local/lib/python3.10/site-packages/oversteer/application.py", line 134, in run
    from oversteer.gui import Gui
  File "/usr/local/lib/python3.10/site-packages/oversteer/gui.py", line 20, in <module>
    from .combined_chart import CombinedChart
  File "/usr/local/lib/python3.10/site-packages/oversteer/combined_chart.py", line 3, in <module>
    from matplotlib.backends.backend_gtk3cairo import FigureCanvasGTK3Cairo as FigureCanvas
ModuleNotFoundError: No module named 'matplotlib.backends.backend_gtk3cairo'

**Comment by berarma** [comment]
It looks like there are missing dependencies. Have you installed rhe required packages for Fedora?

**Comment by Midnight64** [comment]
I ran the install command again, and all dependencies are installed with the exception of python3-distutils i get this error:
Unable to find a match: python3-distutils

**Comment by berarma** [comment]
Try the same command again removing the packages that fail. I don't have a Fedora install to try. You might need to adjust the package list.

**Comment by Midnight64** [comment]
That solved the issue. Thank you.
