### ISSUE TITLE
Wheel test fails on Wii Wheel Wireless

### ISSUE THREAD

**Issue by TylerWDoesStuff** [berarma/oversteer#121]
On the "testing performance parameters at the highest force levels" test, the command line spits out this:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/oversteer/gui.py", line 492, in end_test
    self.show_test_results()
  File "/usr/lib/python3/dist-packages/oversteer/gui.py", line 518, in show_test_results
    self.ui.test_max_decel.set_text(format(self.performance_chart.get_max_decel(), '.0f'))
  File "/usr/lib/python3/dist-packages/oversteer/performance_chart.py", line 63, in get_max_decel
    if t1 >= t2:
TypeError: '>=' not supported between instances of 'float' and 'NoneType'

Wheel: Wii Wheel Wireless
System: Dell G15 5511
OS: Ubuntu 22.10

**Comment by TylerWDoesStuff** [comment]
Aaand nevermind it somehow fixed itself!?
