### ISSUE TITLE
Logitech G29 Driving Force Racing Wheel - No device available.

### ISSUE THREAD

**Issue by princeofgiri** [berarma/oversteer#125]
Error logs :
```
$ oversteer


No device available.
Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 53, in <module>
    sys.exit(app.run(sys.argv))
  File "/usr/lib/python3/dist-packages/oversteer/application.py", line 132, in run
    Gui(self, model, argv)
  File "/usr/lib/python3/dist-packages/oversteer/gui.py", line 99, in __init__
    if not model.device:
AttributeError: 'Model' object has no attribute 'device'
```

dmesg:
```
[ 1946.727179] input: Logitech G29 Driving Force Racing Wheel as /devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb1/1-2/1-2:1.0/0003:046D:C260.000B/input/input30
[ 1946.727491] hid-generic 0003:046D:C260.000B: input,hiddev0,hidraw1: USB HID v1.10 Joystick [Logitech G29 Driving Force Racing Wheel] on usb-0000:04:00.3-2/input0
```

**Comment by berarma** [comment]
You have to set the switch in the wheel to PS3 mode. It won't work in PS4 mode.

**Comment by berarma** [comment]
I've just added a note to the README and fixed the error that prevented the GUI from running.
