### ISSUE TITLE
Python 3.10: Import Error

### ISSUE THREAD

**Issue by mechovation** [berarma/oversteer#126]
Cannot start oversteer on Pop_OS with Python 3.10.  All dependencies installed using apt per the docs.  Error below:

Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 53, in <module>
    sys.exit(app.run(sys.argv))
  File "/usr/lib/python3/dist-packages/oversteer/application.py", line 131, in run
    from oversteer.gui import Gui
  File "/usr/lib/python3/dist-packages/oversteer/gui.py", line 20, in <module>
    from .combined_chart import CombinedChart
  File "/usr/lib/python3/dist-packages/oversteer/combined_chart.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 57, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/usr/lib/python3/dist-packages/matplotlib/figure.py", line 25, in <module>
    from matplotlib import _blocking_input, docstring, projections
  File "/usr/lib/python3/dist-packages/matplotlib/projections/__init__.py", line 58, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/home/eric/.local/lib/python3.10/site-packages/mpl_toolkits/mplot3d/__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "/home/eric/.local/lib/python3.10/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 22, in <module>
    from matplotlib import _api, cbook, _docstring, _preprocess_data
ImportError: cannot import name '_docstring' from 'matplotlib' (/usr/lib/python3/dist-packages/matplotlib/__init__.py)

**Comment by mechovation** [comment]
Yes, I think you hit it exactly.  I just uninstalled matplotlib with apt, installed with pip(3).  Oversteer now launches.  Thanks!
