### ISSUE TITLE
Broken with linux 6.1.8 and above

### ISSUE THREAD

**Issue by eruizc-dev** [berarma/oversteer#130]
I recently updated packages linux and linux-header to latest and realized the software stopped working

**Symptoms**:
 - Software opens
 - Wheel is detected
 - Input is detected and shown in software (like pressing pedals or turning the wheel)
 - Any configuration change has no effect on the wheel (rotation range, autocenter strength, or even running tests)
 
**Setup**:
 - Arch Linux 6.1.8 and above (tested 6.1.8, 6.1.9, and 6.1.11)
 - Logitech G923 (Play Station version)
 - Software installed via AUR

**Patch**:

Downgrade to linux 6.1.6-arch1 and linux-headers 61.6-arch1

### Logs

When I open the software I immediately get these logs:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/oversteer/gtk_handlers.py", line 49, in on_device_changed
    self.controller.change_device(device_id)
  File "/usr/lib/python3.10/site-packages/oversteer/gui.py", line 184, in change_device
    self.model = Model(self.device, self.ui)
  File "/usr/lib/python3.10/site-packages/oversteer/model.py", line 46, in __init__
    self.update_from_device_settings()
  File "/usr/lib/python3.10/site-packages/oversteer/model.py", line 84, in update_from_device_settings
    self.data.update(self.read_device_settings())
  File "/usr/lib/python3.10/site-packages/oversteer/model.py", line 69, in read_device_settings
    'ff_gain': self.device.get_ff_gain(),
  File "/usr/lib/python3.10/site-packages/oversteer/device.py", line 214, in get_ff_gain
    if ecodes.FF_GAIN in capabilities[ecodes.EV_FF]:
KeyError: 21
```

Any attempt to modify settings result in these logs (or similar):

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/oversteer/gtk_handlers.py", line 98, in on_autocenter_value_changed
    self.model.set_autocenter(autocenter)
AttributeError: 'NoneType' object has no attribute 'set_autocenter'
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/oversteer/gtk_handlers.py", line 66, in on_wheel_range_value_changed
    self.model.set_range(wrange)
AttributeError: 'NoneType' object has no attribute 'set_range'
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/oversteer/gui.py", line 447, in input_thread
    self.process_events(events)
  File "/usr/lib/python3.10/site-packages/oversteer/gui.py", line 439, in process_events
    self.on_button_press(button, event.value)
  File "/usr/lib/python3.10/site-packages/oversteer/gui.py", line 341, in on_button_press
    if self.model.get_use_buttons():
AttributeError: 'NoneType' object has no attribute 'get_use_buttons'
```

### Additional notes

Kernel 6.1.7 seems to be broken since it would not detect any input coming from the steering wheel and force-feedback would not work at all. I don't blame that on this software but I thought it was worth mentioning.

**Comment by berarma** [comment]
Have you rebuilt the driver module for 6.1.8?

Please, run `dkms status` and see if the driver module has been compiled for your running kernel.

You can look for messages from the driver module in use with `dmesg`.

**Comment by eruizc-dev** [comment]
I'm currently on 6.1.11, `dkms status` shows the lg4ff for 6.1.11 and a broken one for 6.1.7. Rebuilt and installed everyting with `yay -S new-lg4ff-dkms-git` and 

```sh
# Before
> dkms status
new-lg4ff/0.3.3.r29.ge0ba812, 6.1.11-arch1-1, x86_64: built
new-lg4ff/0.3.3.r29.ge0ba812, 6.1.7-arch1-1, x86_64: built (WARNING! Missing some built modules!)

# After
> dkms status
new-lg4ff/0.3.3.r29.ge0ba812, 6.1.11-arch1-1, x86_64: built
```

I could not find anything relevant in dmesg as the wheel works fine, it's just that I cannot change any settings from this software

**Comment by berarma** [comment]
The Readme from new-lg4ff explains how to check that the driver has been loaded.

Support for the G923 (PS) was added in new-lg4ff 0.4.0 but you have installed 0.3.3. This would explain the module not loading. But it doesn't explain why it worked before.

**Comment by eruizc-dev** [comment]
I managed to get it working by:
 1. Uninstalling the new-lg4ff-dkms-git package from AUR (`yay -Rcs new-lg4ff-dkms-git`)
 2. Installing manually
      a. Clone repo
      b. Run `make && sudo make install && sudo make load`
      c. Reboot

This leads me to assume there's a bug in the AUR installation script, I'll close the issue here and try to get in contact with package maintainers to find the root cause linking any further info back here.

Thank you so much @berarma for you support and the amazing software you built <3
