### ISSUE TITLE
Oversteer won't start, crashing on startup with traceback

### ISSUE THREAD

**Issue by freq-mod** [berarma/oversteer#143]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 176, in require_foreign
    _gi.require_foreign(namespace, symbol)
ModuleNotFoundError: No module named 'gi._gi_cairo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/_backend_gtk.py", line 22, in <module>
    gi.require_foreign("cairo")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 178, in require_foreign
    raise ImportError(str(e))
ImportError: No module named 'gi._gi_cairo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 53, in <module>
    sys.exit(app.run(sys.argv))
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/oversteer/application.py", line 131, in run
    from oversteer.gui import Gui
  File "/usr/lib/python3/dist-packages/oversteer/gui.py", line 20, in <module>
    from .combined_chart import CombinedChart
  File "/usr/lib/python3/dist-packages/oversteer/combined_chart.py", line 3, in <module>
    from matplotlib.backends.backend_gtk3cairo import FigureCanvasGTK3Cairo as FigureCanvas
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3cairo.py", line 5, in <module>
    from .backend_gtk3 import Gtk, FigureCanvasGTK3, _BackendGTK3
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3.py", line 29, in <module>
    from . import _backend_gtk
  File "/usr/lib/python3/dist-packages/matplotlib/backends/_backend_gtk.py", line 24, in <module>
    raise ImportError("Gtk-based backends require cairo") from e
ImportError: Gtk-based backends require cairo

libcairo2-dev has been installed. Debian 12 Bookworm, oversteer self-built

**Comment by freq-mod** [comment]
pycairo was also installed, via pip

**Comment by berarma** [comment]
I think `python3-matplotlib` should require `python3-cairo` but it doesn't.

Can you try installing `python3-cairo` from the package manager?

Use the package manager rather than pip to avoid mixing incompatible dependencies.

**Comment by usbalbin** [comment]
For me(on ubuntu) running
`sudo apt install python3-gi python3-gi-cairo`
seems to fix that error
