### ISSUE TITLE
T300RS "TypeError: access: path should be string, bytes or os.PathLike, not NoneType"

### ISSUE THREAD

**Issue by snorkellingcactus** [berarma/oversteer#145]
Hi. I've tried latest oversteer tag 0.7.2 and master

0.7.2 starts but throws the error and all gui knobs are noop
master dont even start the gui

master 7efdcc38627f33ceb520d95e75ac6c1f6a06f852 log:

```
$:oversteer --debug
DEBUG:root:update_device_list: input-pci-0000_00_14_0-usb-0_3_1_0
DEBUG:root:NAME: "Thrustmaster Thrustmaster T300RS Racing wheel"
DEBUG:root:update_device_list: None
DEBUG:root:Devices: {'input-pci-0000_00_14_0-usb-0_3_1_0': <oversteer.device.Device object at 0x7fedb977f6a0>}
Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 53, in <module>
    sys.exit(app.run(sys.argv))
  File "/usr/x86_64-pc-linux-gnu/lib/python3.10/site-packages/oversteer/application.py", line 103, in run
    model = Model(device)
  File "/usr/x86_64-pc-linux-gnu/lib/python3.10/site-packages/oversteer/model.py", line 48, in __init__
    self.set_device(device)
  File "/usr/x86_64-pc-linux-gnu/lib/python3.10/site-packages/oversteer/model.py", line 56, in set_device
    self.update_from_device_settings()
  File "/usr/x86_64-pc-linux-gnu/lib/python3.10/site-packages/oversteer/model.py", line 91, in update_from_device_settings
    self.data.update(self.read_device_settings())
  File "/usr/x86_64-pc-linux-gnu/lib/python3.10/site-packages/oversteer/model.py", line 77, in read_device_settings
    'autocenter': self.device.get_autocenter(),
  File "/usr/x86_64-pc-linux-gnu/lib/python3.10/site-packages/oversteer/device.py", line 187, in get_autocenter
    capabilities = self.get_capabilities()
  File "/usr/x86_64-pc-linux-gnu/lib/python3.10/site-packages/oversteer/device.py", line 373, in get_capabilities
    return self.get_input_device().capabilities()
  File "/usr/x86_64-pc-linux-gnu/lib/python3.10/site-packages/oversteer/device.py", line 368, in get_input_device
    if os.access(self.dev_name, os.R_OK):
TypeError: access: path should be string, bytes or os.PathLike, not NoneType
```
 
 dmesg when plugging the wheel:
 
```
[Sun Jul 30 13:43:36 2023] usb 1-3: new full-speed USB device number 11 using xhci_hcd
[Sun Jul 30 13:43:36 2023] usb 1-3: New USB device found, idVendor=044f, idProduct=b65d, bcdDevice= 1.00
[Sun Jul 30 13:43:36 2023] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[Sun Jul 30 13:43:36 2023] usb 1-3: Product: Thrustmaster FFB Wheel
[Sun Jul 30 13:43:36 2023] usb 1-3: Manufacturer: Thrustmaster
[Sun Jul 30 13:43:36 2023] input: Thrustmaster Thrustmaster FFB Wheel as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0/0003:044F:B65D.0009/input/input29
[Sun Jul 30 13:43:36 2023] hid-thrustmaster 0003:044F:B65D.0009: input,hidraw3: USB HID v1.00 Gamepad [Thrustmaster Thrustmaster FFB Wheel] on usb-0000:00:14.0-3/input0
[Sun Jul 30 13:43:36 2023] hid-thrustmaster 0003:044F:B65D.0009: Wheel with model id 0x206 is a Thrustmaster T300RS
[Sun Jul 30 13:43:36 2023] usb 1-3: USB disconnect, device number 11
[Sun Jul 30 13:43:36 2023] hid-thrustmaster 0003:044F:B65D.0009: Success?! The wheel should have been initialized!
[Sun Jul 30 13:43:37 2023] usb 1-3: new full-speed USB device number 12 using xhci_hcd
[Sun Jul 30 13:43:37 2023] usb 1-3: New USB device found, idVendor=044f, idProduct=b66e, bcdDevice= 1.00
[Sun Jul 30 13:43:37 2023] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[Sun Jul 30 13:43:37 2023] usb 1-3: Product: Thrustmaster T300RS Racing wheel
[Sun Jul 30 13:43:37 2023] usb 1-3: Manufacturer: Thrustmaster
[Sun Jul 30 13:43:37 2023] input: Thrustmaster Thrustmaster T300RS Racing wheel as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0/0003:044F:B66E.000A/input/input30
[Sun Jul 30 13:43:37 2023] tmff2 0003:044F:B66E.000A: input,hidraw3: USB HID v1.11 Joystick [Thrustmaster Thrustmaster T300RS Racing wheel] on usb-0000:00:14.0-3/input0
[Sun Jul 30 13:43:37 2023] tmff2 0003:044F:B66E.000A: force feedback for T300RS
```

input29 does not exists
udevadm info of input30 is:

```
$:udevadm info  /sys//devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0/0003:044F:B66E.000A/input/input30
P: //devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0/0003:044F:B66E.000A/input/input30
E: ABS=30027
E: DEVPATH=//devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0/0003:044F:B66E.000A/input/input30
E: EV=20001b
E: FF=31fff0000 0
E: ID_BUS=usb
E: ID_FOR_SEAT=input-pci-0000_00_14_0-usb-0_3_1_0
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_MODEL=Thrustmaster_T300RS_Racing_wheel
E: ID_MODEL_ENC=Thrustmaster\x20T300RS\x20Racing\x20wheel
E: ID_MODEL_ID=b66e
E: ID_PATH=pci-0000:00:14.0-usb-0:3:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_3_1_0
E: ID_REVISION=0100
E: ID_SERIAL=Thrustmaster_Thrustmaster_T300RS_Racing_wheel
E: ID_TYPE=hid
E: ID_USB_DRIVER=usbhid
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=Thrustmaster
E: ID_VENDOR_ENC=Thrustmaster
E: ID_VENDOR_ID=044f
E: KEY=1fff00000000 0 0 0 0
E: MODALIAS=input:b0003v044FpB66Ee0111-e0,1,3,4,15,k120,121,122,123,124,125,126,127,128,129,12A,12B,12C,ra0,1,2,5,10,11,m4,lsf50,51,52,53,54,55,56,57,58,59,5A,5B,5C,60,61,w
E: MSC=10
E: NAME="Thrustmaster Thrustmaster T300RS Racing wheel"
E: PHYS="usb-0000:00:14.0-3/input0"
E: PRODUCT=3/44f/b66e/111
E: PROP=0
E: SUBSYSTEM=input
E: TAGS=:seat:
E: UNIQ=""
E: USEC_INITIALIZED=1357394455
```

i've installed latest hid-tmmf2 010c0d986d8d75ff2727d164c8c41b08b33549a9

Thanks for your help in advance

**Comment by snorkellingcactus** [comment]
I was looking this error may be someway related to https://github.com/berarma/oversteer/issues/55

**Comment by snorkellingcactus** [comment]
I put a comment on device.py:66
`print("checked_device_file: path:", path)`
and i think for some reason the driver is not listing autocenter on sys.

last print before error shows:
"checked_device_file: path: /sys/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/0003:044F:B66E.000B/autocenter"

**Comment by snorkellingcactus** [comment]
I copy pasted some gain code from the hid-tmmf2 and udev.d rule to provide autocenter an now the weel works on dirt2 but oversteer is still getting errors

**Comment by berarma** [comment]
Oversteer isn't getting all the info it should get from udev. Can you find the device in `/dev/input/by-id`? What does `udevam info` show about the eventXX device?

These errors shouldn't affect games. The only thing you need to play games with the wheel is the driver. tmff2 in this case.

**Comment by snorkellingcactus** [comment]
```
[Mon Jul 31 18:02:52 2023] input: Thrustmaster Thrustmaster T300RS Racing wheel as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/0003:044F:B66E.000B/input/input31
[Mon Jul 31 18:02:52 2023] tmff2 0003:044F:B66E.000B: input,hidraw3: USB HID v1.11 Joystick [Thrustmaster Thrustmaster T300RS Racing wheel] on usb-0000:00:14.0-4/input0
```

```
$:ls -l /dev/input/by-id/
total 0
lrwxrwxrwx 1 root root 10 Jul 31 15:44 usb-Chicony_Electronics_Co._Ltd._HD_User_Facing_0001-event-if00 -> ../event12
lrwxrwxrwx 1 root root  9 Jul 31 15:47 usb-musinou_J2M_SIMRACING_HIDNH-if02-event-joystick -> ../event7
lrwxrwxrwx 1 root root  6 Jul 31 15:47 usb-musinou_J2M_SIMRACING_HIDNH-if02-joystick -> ../js0
lrwxrwxrwx 1 root root 10 Jul 31 18:02 usb-Thrustmaster_Thrustmaster_T300RS_Racing_wheel-event-joystick -> ../event17
lrwxrwxrwx 1 root root  6 Jul 31 18:02 usb-Thrustmaster_Thrustmaster_T300RS_Racing_wheel-joystick -> ../js2
lrwxrwxrwx 1 root root  9 Jul 31 15:47 usb-Thustmaster_T500_RS_Gear_Shift-event-joystick -> ../event8
lrwxrwxrwx 1 root root  6 Jul 31 15:47 usb-Thustmaster_T500_RS_Gear_Shift-joystick -> ../js1
```

```
$:udevadm info /dev/input/by-id/usb-Thrustmaster_Thrustmaster_T300RS_Racing_wheel-event-joystick
P: /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/0003:044F:B66E.000B/input/input31/event17
N: input/event17
S: input/by-id/usb-Thrustmaster_Thrustmaster_T300RS_Racing_wheel-event-joystick
S: input/by-path/pci-0000:00:14.0-usb-0:4:1.0-event-joystick
E: DEVLINKS=/dev/input/by-id/usb-Thrustmaster_Thrustmaster_T300RS_Racing_wheel-event-joystick /dev/input/by-path/pci-0000:00:14.0-usb-0:4:1.0-event-joystick
E: DEVNAME=/dev/input/event17
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/0003:044F:B66E.000B/input/input31/event17
E: ID_BUS=usb
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_MODEL=Thrustmaster_T300RS_Racing_wheel
E: ID_MODEL_ENC=Thrustmaster\x20T300RS\x20Racing\x20wheel
E: ID_MODEL_ID=b66e
E: ID_PATH=pci-0000:00:14.0-usb-0:4:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_4_1_0
E: ID_REVISION=0100
E: ID_SERIAL=Thrustmaster_Thrustmaster_T300RS_Racing_wheel
E: ID_TYPE=hid
E: ID_USB_DRIVER=usbhid
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=Thrustmaster
E: ID_VENDOR_ENC=Thrustmaster
E: ID_VENDOR_ID=044f
E: LIBINPUT_DEVICE_GROUP=3/44f/b66e:usb-0000:00:14.0-4
E: MAJOR=13
E: MINOR=81
E: SUBSYSTEM=input
E: USEC_INITIALIZED=8276532945
```

**Comment by berarma** [comment]
For some reason your eventXX device doesn't have ID_FOR_SEAT set. Which distro do you use? Have you changed configurations related to udev or logind?

You can list seats in your systems with `loginctl` then I'd like to see the output of `loginctl seat-status seat0`, where `seat0` should be the name of your seat.

I'm no expert in that system-level stuff so any additional help it's appreciated.

**Comment by berarma** [comment]
Please, can you test the latest master?

**Comment by snorkellingcactus** [comment]
Yes i have a gentoo like distro, exherbo, i have elogind and i had problems with polkit, specifically the lxqt polkit agent hanging or freezing at the time of using pkexec.
The default pkttyagent failed with

```
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
```

There wasn't a seat assigned to my X session before when i used xinit, but now using sddm it's listed

```
loginctl 
SESSION  UID USER   SEAT  TTY 
      2 1000 cactus seat0 
      3    0 root   seat0 tty1

2 sessions listed.
```

However i guess there is still some issue related to that on my system since the pkttyagent issue persists

I planned to see and touch some polkit agent code to debug and reach the root issue

I'm also not an expert but trying to do my best

I'l try later master and `loginctl seat-status seat0` with the wheel plugged

**Comment by berarma** [comment]
The new device detection implemented in master should work independently of seats. I think it's more correct too. It should work without any other changes to your system.

**Comment by snorkellingcactus** [comment]
It works but there is no feedback about it on the ui no matter what i press on the wheel

```
loginctl seat-status seat0
seat0
        Sessions: *2
         Devices:
                  ├─/sys/devices/LNXSYSTM:00/LNXPWRBN:00/input/input3
                  │ input:input3 "Power Button"
                  ├─/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:01/input/input5
                  │ input:input5 "Video Bus"
                  ├─/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00/LNXVIDEO:00/input/input4
                  │ input:input4 "Video Bus"
                  ├─/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:20/PNP0C09:00/10251229:00/input/input7
                  │ input:input7 "Acer Wireless Radio Control"
                  ├─/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input1
                  │ input:input1 "Power Button"
                  ├─/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00/input/input0
                  │ input:input0 "Lid Switch"
                  ├─/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0E:00/input/input2
                  │ input:input2 "Sleep Button"
                  ├─/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card1
                  │ [MASTER] drm:card1
                  ├─/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1
                  │ sound:card1 "NVidia"
                  │ ├─/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input11
                  │ │ input:input11 "HDA NVidia HDMI"
                  │ └─/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input12
                  │   input:input12 "HDA NVidia HDMI"
                  ├─/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.2/usb3
                  │ usb:usb3
                  ├─/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.2/usb4
                  │ usb:usb4
                  ├─/sys/devices/pci0000:00/0000:00:02.0/drm/card0
                  │ [MASTER] drm:card0
                  │ ├─/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-1
                  │ │ [MASTER] drm:card0-DP-1
                  │ ├─/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-2
                  │ │ [MASTER] drm:card0-DP-2
                  │ ├─/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-3
                  │ │ [MASTER] drm:card0-DP-3
                  │ ├─/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-HDMI-A-1
                  │ │ [MASTER] drm:card0-HDMI-A-1
                  │ ├─/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-HDMI-A-2
                  │ │ [MASTER] drm:card0-HDMI-A-2
                  │ └─/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1
                  │   [MASTER] drm:card0-eDP-1
                  │   └─/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight
                  │     backlight:intel_backlight
                  ├─/sys/devices/pci0000:00/0000:00:02.0/graphics/fb0
                  │ graphics:fb0 "i915drmfb"
                  ├─/sys/devices/pci0000:00/0000:00:14.0/usb1
                  │ usb:usb1
                  │ ├─/sys/devices/pci0000:00/0000:00:14.0/usb1/1-4
                  │ │ usb:1-4
                  │ │ └─/sys/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/0003:044F:B66E.0004/input/input24
                  │ │   input:input24 "Thrustmaster Thrustmaster T300RS Racing wheel"
                  │ └─/sys/devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/input/input10
                  │   input:input10 "HD User Facing: HD User Facing"
                  ├─/sys/devices/pci0000:00/0000:00:14.0/usb2
                  │ usb:usb2
                  ├─/sys/devices/pci0000:00/0000:00:14.3/leds/phy0-led
                  │ leds:phy0-led
                  ├─/sys/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-11/i2c-SYNA7DB5:00/0018:06CB:CD41.0001/input/input16
                  │ input:input16 "SYNA7DB5:00 06CB:CD41 Mouse"
                  ├─/sys/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-11/i2c-SYNA7DB5:00/0018:06CB:CD41.0001/input/input17
                  │ input:input17 "SYNA7DB5:00 06CB:CD41 Touchpad"
                  ├─/sys/devices/pci0000:00/0000:00:1f.3/sound/card0
                  │ sound:card0 "PCH"
                  │ ├─/sys/devices/pci0000:00/0000:00:1f.3/sound/card0/input19
                  │ │ input:input19 "HDA Intel PCH Front Headphone"
                  │ └─/sys/devices/pci0000:00/0000:00:1f.3/sound/card0/input20
                  │   input:input20 "HDA Intel PCH HDMI"
                  ├─/sys/devices/platform/i8042/serio0/input/input6
                  │ input:input6 "AT Translated Set 2 keyboard"
                  │ ├─/sys/devices/platform/i8042/serio0/input/input6/input6::capslock
                  │ │ leds:input6::capslock
                  │ ├─/sys/devices/platform/i8042/serio0/input/input6/input6::numlock
                  │ │ leds:input6::numlock
                  │ └─/sys/devices/platform/i8042/serio0/input/input6/input6::scrolllock
                  │   leds:input6::scrolllock
                  ├─/sys/devices/platform/pcspkr/input/input8
                  │ input:input8 "PC Speaker"
                  ├─/sys/devices/virtual/input/input9
                  │ input:input9 "Acer WMI hotkeys"
                  └─/sys/devices/virtual/misc/uinput
                    misc:uinput
```

```
$:oversteer --debug
DEBUG:root:update_device_list: /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/0003:044F:B66E.0004/input/input24/event17 /dev/input/event17
DEBUG:root:/dev/input/event17: ID_VENDOR_ID: 044f ID_MODEL_ID: b66e
DEBUG:root:Devices: {'/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/0003:044F:B66E.0004/input/input24/event17': <oversteer.device.Device object at 0x7f75fcd15960>}
DEBUG:matplotlib:matplotlib data path: /usr/x86_64-pc-linux-gnu/lib/python3.10/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/home/cactus/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:matplotlib:CACHEDIR=/home/cactus/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/cactus/.cache/matplotlib/fontlist-v330.json
```

**Comment by berarma** [comment]
Please, can you use the `evtest` command to see which events are generated for the wheel, the pedals and the buttons. I thought we got this already mapped but I could be wrong.

**Comment by snorkellingcactus** [comment]
However setting params seems to work, at least autocenter

**Comment by snorkellingcactus** [comment]
```
 $:evtest 
No device specified, trying to scan all of /dev/input/event*
Not running as root, no devices may be available.
Available devices:
/dev/input/event0:      Lid Switch
/dev/input/event1:      Power Button
/dev/input/event2:      Sleep Button
/dev/input/event3:      Power Button
/dev/input/event4:      Video Bus
/dev/input/event5:      Video Bus
/dev/input/event6:      AT Translated Set 2 keyboard
/dev/input/event7:      Acer Wireless Radio Control
/dev/input/event8:      PC Speaker
/dev/input/event9:      Acer WMI hotkeys
/dev/input/event10:     HD User Facing: HD User Facing
/dev/input/event11:     SYNA7DB5:00 06CB:CD41 Mouse
/dev/input/event12:     SYNA7DB5:00 06CB:CD41 Touchpad
/dev/input/event13:     HDA NVidia HDMI
/dev/input/event14:     HDA NVidia HDMI
/dev/input/event15:     HDA Intel PCH Front Headphone
/dev/input/event16:     HDA Intel PCH HDMI
/dev/input/event17:     Thrustmaster Thrustmaster T300RS Racing wheel
/dev/input/event18:     Thustmaster T500 RS Gear Shift
Select the device event number [0-18]: 17
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x44f product 0xb66e version 0x111
Input device name: "Thrustmaster Thrustmaster T300RS Racing wheel"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 288 (BTN_TRIGGER)
    Event code 289 (BTN_THUMB)
    Event code 290 (BTN_THUMB2)
    Event code 291 (BTN_TOP)
    Event code 292 (BTN_TOP2)
    Event code 293 (BTN_PINKIE)
    Event code 294 (BTN_BASE)
    Event code 295 (BTN_BASE2)
    Event code 296 (BTN_BASE3)
    Event code 297 (BTN_BASE4)
    Event code 298 (BTN_BASE5)
    Event code 299 (BTN_BASE6)
    Event code 300 (?)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value  33002
      Min        0
      Max    65535
      Fuzz     255
      Flat    4095
    Event code 1 (ABS_Y)
      Value   1023
      Min        0
      Max     1023
      Fuzz       3
      Flat      63
    Event code 2 (ABS_Z)
      Value   1023
      Min        0
      Max     1023
      Fuzz       3
      Flat      63
    Event code 5 (ABS_RZ)
      Value   1023
      Min        0
      Max     1023
      Fuzz       3
      Flat      63
    Event code 16 (ABS_HAT0X)
      Value      0
      Min       -1
      Max        1
    Event code 17 (ABS_HAT0Y)
      Value      0
      Min       -1
      Max        1
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
  Event type 21 (EV_FF)
    Event code 80 (FF_RUMBLE)
    Event code 81 (FF_PERIODIC)
    Event code 82 (FF_CONSTANT)
    Event code 83 (FF_SPRING)
    Event code 84 (FF_FRICTION)
    Event code 85 (FF_DAMPER)
    Event code 86 (FF_INERTIA)
    Event code 87 (FF_RAMP)
    Event code 88 (FF_SQUARE)
    Event code 89 (FF_TRIANGLE)
    Event code 90 (FF_SINE)
    Event code 91 (FF_SAW_UP)
    Event code 92 (FF_SAW_DOWN)
    Event code 96 (FF_GAIN)
    Event code 97 (FF_AUTOCENTER)
Properties:
Testing ... (interrupt to exit)
```

**Comment by snorkellingcactus** [comment]
Hi.

The problem is the `get_id` of `Device`
Firstly, it references the old `seat_id` part, so it's none
Second, the id's used on the array `DeviceManager.devices` is `udevice.device_path`
But the value of `Device.device_path` you store is the basename, the directory, not the same as `udevice.device_path`
If i set `get_id` to `return self.device_id`
and add `'device_id': id,` on `update_device_list` it just works

Hope i explained myself

What do you think ?

**Comment by snorkellingcactus** [comment]
I still have issues. Settinng some params goes (after trying without success the file on the sys directory) through writing the device specifying a capability and his value. Those ones works

But others like range goes only through the sys directory files, like range, those ones doesn't work

**Comment by snorkellingcactus** [comment]
Solved by adding one more `'/device'`
On
`os.path.join(udevice.sys_path, 'device', 'device')`

Not sure it's how should be done, if there is some wrong on my system, but with that it's working

**Comment by snorkellingcactus** [comment]
Seems it all works now on master. Thanks you so much
