### ISSUE TITLE
Running oversteer in Raspberry Pi 4

### ISSUE THREAD

**Issue by TalalSultan** [berarma/oversteer#219]
i downloaded all the dep and installed and built the oversteer but when i try to run any commands i get this error

```
oversteer --center-wheel
Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 53, in <module>
    sys.exit(app.run(sys.argv))
  File "/usr/local/lib/python3/dist-packages/oversteer/application.py", line 103, in run
    model = Model(device)
  File "/usr/local/lib/python3/dist-packages/oversteer/model.py", line 48, in __init__
    self.set_device(device)
  File "/usr/local/lib/python3/dist-packages/oversteer/model.py", line 56, in set_device
    self.update_from_device_settings()
  File "/usr/local/lib/python3/dist-packages/oversteer/model.py", line 91, in update_from_device_settings
    self.data.update(self.read_device_settings())
  File "/usr/local/lib/python3/dist-packages/oversteer/model.py", line 76, in read_device_settings
    'ff_gain': self.device.get_ff_gain(),
  File "/usr/local/lib/python3/dist-packages/oversteer/device.py", line 214, in get_ff_gain
    capabilities = self.get_capabilities()
  File "/usr/local/lib/python3/dist-packages/oversteer/device.py", line 373, in get_capabilities
    return self.get_input_device().capabilities()
AttributeError: 'NoneType' object has no attribute 'capabilities'
```

even though it detect the device when i put oversteer --list 

```
oversteer --list
Devices found:
  /dev/input/event2: 046d G27 Racing Wheel
```

i dont konw if the program even runs in Raspberry Pi if not does anyone knows other programs that works ?

**Comment by berarma** [comment]
Please run with `--debug` switch.

**Comment by TalalSultan** [comment]
i solved it, my device had no accuss to inputs so i just added myself using 

`sudo usermod -aG input $(whoami)
`
