### ISSUE TITLE
Error while runing oversteer

### ISSUE THREAD

**Issue by zekemx** [berarma/oversteer#233]
Hello,

Any ideas on how to fix this?

$ oversteer

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/bin/oversteer", line 53, in <module>
    sys.exit(app.run(sys.argv))
  File "/usr/lib/python3.12/site-packages/oversteer/application.py", line 131, in run
    from oversteer.gui import Gui
  File "/usr/lib/python3.12/site-packages/oversteer/gui.py", line 20, in <module>
    from .combined_chart import CombinedChart
  File "/usr/lib/python3.12/site-packages/oversteer/combined_chart.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib64/python3.12/site-packages/matplotlib/__init__.py", line 161, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/usr/lib64/python3.12/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/usr/lib64/python3.12/site-packages/matplotlib/colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/usr/lib64/python3.12/site-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/usr/lib64/python3.12/site-packages/matplotlib/ticker.py", line 143, in <module>
    from matplotlib import transforms as mtransforms
  File "/usr/lib64/python3.12/site-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):
  File "/usr/bin/oversteer", line 53, in <module>
    sys.exit(app.run(sys.argv))
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/oversteer/application.py", line 131, in run
    from oversteer.gui import Gui
  File "/usr/lib/python3.12/site-packages/oversteer/gui.py", line 20, in <module>
    from .combined_chart import CombinedChart
  File "/usr/lib/python3.12/site-packages/oversteer/combined_chart.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib64/python3.12/site-packages/matplotlib/__init__.py", line 161, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/usr/lib64/python3.12/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/usr/lib64/python3.12/site-packages/matplotlib/colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/usr/lib64/python3.12/site-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/usr/lib64/python3.12/site-packages/matplotlib/ticker.py", line 143, in <module>
    from matplotlib import transforms as mtransforms
  File "/usr/lib64/python3.12/site-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import

**Comment by berarma** [comment]
Which distro are you using? All your issues seem to be related to your distro, and I don't think I can help much with it, but maybe someone will.

**Comment by zekemx** [comment]
Hello Berarma

I am using Mageia 10 Cauldron (dev), I did some test on mageia 9 and it works so I also guess this is a distro problem.  Today I confirmed on another mageia 9 and 10  and it also fails on 10.

I sent you a message because of this part of the error:

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

Regards and thanks for your great job. I actually packaged Oversteer for blogdrake unofficial mageia repos.

**Comment by berarma** [comment]
It seems your distribution has a mix of modules compiled using NumPy 1.x and 2.1. An application using a module compiled for 1.x can't use at the same time a module compiled for 2.1. Normally, a distribution will compile all modules using the same NumPy version or at least offer the modules compiled using both and the user can choose which version to install.

**Comment by IcePanorama** [comment]
Experiencing this exact same issue on Fedora Linux 40 (Linux 6.10.9-200.fc40.x86_64).
