### ISSUE TITLE
Failed to launch

### ISSUE THREAD

**Issue by Hexality** [berarma/oversteer#237]
```
oversteer
Traceback (most recent call last):
  File "/usr/bin/oversteer", line 51, in <module>
    from oversteer.application import Application
  File "/usr/lib/python3.12/site-packages/oversteer/application.py", line 6, in <module>
    from .device_manager import DeviceManager
  File "/usr/lib/python3.12/site-packages/oversteer/device_manager.py", line 5, in <module>
    from .device import Device
  File "/usr/lib/python3.12/site-packages/oversteer/device.py", line 1, in <module>
    from evdev import ecodes, InputDevice
ModuleNotFoundError: No module named 'evdev'
```

**Comment by berarma** [comment]
Have you installed the dependencies in the README?

**Comment by Hexality** [comment]
yep

**Comment by Hexality** [comment]
I'm selling my G27 anyways so, doesn't matter anymore, but thanks.
