### ISSUE TITLE
Unsupported Locale setting

### ISSUE THREAD

**Issue by pantalonielettrici** [berarma/oversteer#239]
Can't run Oversteer, getting: 

```
Traceback (most recent call last):
  File "/app/bin/oversteer", line 48, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.11/locale.py", line 627, in setlocale
    return _setlocale(category, locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
locale.Error: unsupported locale setting
```

**Comment by berarma** [comment]
The locale set in your system is invalid. You either have to change it to one listed in your system as valid, or generate a new locale.
