### ISSUE TITLE
Exception with g923 logitech when runing test

### ISSUE THREAD

**Issue by matevoux** [berarma/oversteer#247]
Hellow 
When i try to use oversteer (flatpack version) to configure G923 from logitech (lsub :ID 046d:c26e Logitech, Inc. G923 Racing Wheel for Xbox One and PC)  no option is avalaible and test throw this execption :

> jeanseb@shinobee:~$ flatpak run io.github.berarma.Oversteer 
Exception in thread Thread-3 (test1):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lib/python3.11/site-packages/oversteer/test.py", line 129, in test1
    left_effect = self.create_left_effect(0)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/oversteer/test.py", line 67, in create_left_effect
    left_effect.id = self.input_device.upload_effect(left_effect)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/evdev/device.py", line 340, in upload_effect
    ff_id = _input.upload_effect(self.fd, data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 38] Fonction non implantée

**Comment by matevoux** [comment]
seem to be a kernel issue ( debian)

**Comment by berarma** [comment]
It looks like your wheel is in an incompatible mode. According to [this list](https://github.com/JacKeTUs/linux-steering-wheels), the product id shoud be 046d:c26d but it's 046d:c62e instead. There could be a switch in the wheel to change modes, but if it doesn't, a usb-modeswitch command could do it. It could only be a matter of updating your Linux kernel if it's older than 6.3.

**Comment by berarma** [comment]
This command is needed to switch the wheel to PC mode:

`sudo usb_modeswitch -v 046d -p c26d -M 0f00010142 -C 0x03 -m 01 -r 01`
