### ISSUE TITLE
Listing devices does not work with latest

### ISSUE THREAD

**Issue by kaixiong** [berarma/oversteer#25]
Oversteer calls `DeviceManager.list_devices()` which no longer exists.

```
kaixiong@XXX:~/Documents/sources/oversteer$ oversteer --list
Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 51, in <module>
    sys.exit(app.run(sys.argv))
  File "/usr/lib/python3.8/site-packages/oversteer/application.py", line 63, in run
    device_list = device_manager.list_devices()
AttributeError: 'DeviceManager' object has no attribute 'list_devices'
```

**Comment by berarma** [comment]
It's been fixed. Thanks!

**Comment by kaixiong** [comment]
I can confirm the fix, thanks!
