### ISSUE TITLE
Can't save profiles

### ISSUE THREAD

**Issue by pwasiewi** [berarma/oversteer#28]
I have errors while saving profiles (Gentoo python 3.7)
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/oversteer/gtk_ui.py", line 483, in on_save_profile_as_clicked
    self.gui.save_profile_as(profile_name)
  File "/usr/lib/python3.7/site-packages/oversteer/gui.py", line 251, in save_profile_as
    self.save_profile(profile_file)
  File "/usr/lib/python3.7/site-packages/oversteer/gui.py", line 237, in save_profile
    profile = Profile(self.device.save_settings())
  File "/usr/lib/python3.7/site-packages/oversteer/profiles.py", line 8, in __init__
    self.import_settings(data)
  File "/usr/lib/python3.7/site-packages/oversteer/profiles.py", line 36, in import_settings
    self.config['DEFAULT'] = {**self.config['DEFAULT'], **data}
  File "/usr/lib/python3.7/configparser.py", line 971, in __setitem__
    self.read_dict({key: value})
  File "/usr/lib/python3.7/configparser.py", line 753, in read_dict
    self.set(section, key, value)
  File "/usr/lib/python3.7/configparser.py", line 1197, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/lib/python3.7/configparser.py", line 1182, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
```

**Comment by berarma** [comment]
I think you're using an old version of Oversteer, at some commit before releasing version 0.5.x. I did some testing for the release and fixed several regressions. Please update your code.

**Comment by Helge102** [comment]
I can confirm the problem.
I Just updated from 0.4.1 to 0.5.0 and Profiles doesnt work anymore.
Changes will take effect, but clicking the 'save' button will reset everything.
Back on 0.4.1 everythings fine.

One Question:
Where is the storage location of the profiles?

Thanks for your great work.
I love it.

Helge

**Comment by berarma** [comment]
> I can confirm the problem.
> I Just updated from 0.4.1 to 0.5.0 and Profiles doesnt work anymore.
> Changes will take effect, but clicking the 'save' button will reset everything.
> Back on 0.4.1 everythings fine.
> 
> One Question:
> Where is the storage location of the profiles?
> 
> Thanks for your great work.
> I love it.
> 
> Helge

Hi @Helge102.

This is a different issue so I've moved your report to a new issue (#29).

**Comment by berarma** [comment]
Please reopen if the issue persists.
