### ISSUE TITLE
Application won't start

### ISSUE THREAD

**Issue by patkoscsaba** [berarma/oversteer#32]
When I try to start oversteer with the --gui or -g options, I am getting this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 51, in <module>
    sys.exit(app.run(sys.argv))
  File "/usr/lib/python3.8/site-packages/oversteer/application.py", line 106, in run
    Gui(self)
  File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 70, in __init__
    self.ui = GtkUi(self)
  File "/usr/lib/python3.8/site-packages/oversteer/gtk_ui.py", line 20, in __init__
    Gtk.StyleContext.add_provider_for_screen(
TypeError: Argument 0 does not allow None as a value
```
From CLI with parameters it seems to be working though ... for example the --list command works
```
csaba@csaba-pc:~/Personal/oversteer> oversteer --list
Devices found:
  /dev/input/event8: Logitech G29 Driving Force Racing Wheel
```

Also, if I try to set some value, it says I should copy a file to get udev permissions, but it doesn't specify the file's name and path.
```
csaba@csaba-pc:~/Personal/oversteer> oversteer --range 300 /dev/input/event8
You don't have the required permissions to change your wheel settings. You can fix it yourself by copying the {} file to the /usr/local/share/oversteer/udev/99-logitech-wheel-perms.rules directory and rebooting.
```

Notes:
1. I am using OpenSuse Thumbleweed
2. The weel works without issues in games like DiRT Rally 2 through Steam and Proton
3. I tried fftest and it works
4. I tried using pyLinuxWheel and it works (however I have issues with that application not displaying fonts at all).

**Comment by berarma** [comment]
> When I try to start oversteer with the --gui or -g options, I am getting this error:

It seems it can't find a display. Are you launching it from some console dettached in some way from your graphical display? Or do you have some unusual display configuration?

> Also, if I try to set some value, it says I should copy a file to get udev permissions, but it doesn't specify the file's name and path.

Yes, this is a known problem. Usually, you would get properly asked in the graphical interface.

The file is in the `data/udev/` directory in the project, and it has to be copied to `/etc/udev/rules.d/`. Then restart the system.

**Comment by patkoscsaba** [comment]
> It seems it can't find a display. Are you launching it from some console dettached in some way from your graphical display? Or do you have some unusual display configuration?

No. I am using KDE though. I use Konsole as my terminal and I can start graphical apps from there. Any particular command I could run that would help you debug this? I also have GTK libraries installed as other applications need them. Code compile succeeds without errors. I have an Nvidia video card.
Please be free to ask for any command/logs your may need. I am long time Linux user, so I can easily provide whatever you need.

> Yes, this is a known problem. Usually, you would get properly asked in the graphical interface.
> 
> The file is in the `data/udev/` directory in the project, and it has to be copied to `/etc/udev/rules.d/`. Then restart the system.

Thanks for the details. I'll do the copy when I have time for a reboot.

**Comment by berarma** [comment]
@patkoscsaba, please, can you test PR #33? You need to checkout branch gdkfix.

**Comment by patkoscsaba** [comment]
Finally I had the time to try this out, it still won't work. Below is all I did. I needed to install a couple extra python libraries as well. And I installed them.

```
csaba@csaba-pc:~/Personal/oversteer> git fetch -a
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 63 (delta 39), reused 55 (delta 33), pack-reused 0
Unpacking objects: 100% (63/63), 41.78 KiB | 470.00 KiB/s, done.
From https://github.com/berarma/oversteer
   5aed6f5..31601ef  master     -> origin/master
 * [new branch]      gdkfix     -> origin/gdkfix
 * [new tag]         0.5.3      -> 0.5.3
csaba@csaba-pc:~/Personal/oversteer> git checkout gdkfix
Branch 'gdkfix' set up to track remote branch 'gdkfix' from 'origin'.
Switched to a new branch 'gdkfix'
csaba@csaba-pc:~/Personal/oversteer> git pull
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

Already up to date.
csaba@csaba-pc:~/Personal/oversteer> rm -rf ./build/
csaba@csaba-pc:~/Personal/oversteer> meson build
The Meson build system
Version: 0.55.1
Source dir: /home/csaba/Personal/oversteer
Build dir: /home/csaba/Personal/oversteer/build
Build type: native build
Project name: oversteer
Project version: 0.5.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)

meson.build:17:4: ERROR: Problem encountered: Required Python3 module 'matplotlib' not found

A full log can be found at /home/csaba/Personal/oversteer/build/meson-logs/meson-log.txt
csaba@csaba-pc:~/Personal/oversteer> meson build
The Meson build system
Version: 0.55.1
Source dir: /home/csaba/Personal/oversteer
Build dir: /home/csaba/Personal/oversteer/build
Build type: native build
Project name: oversteer
Project version: 0.5.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)

meson.build:17:4: ERROR: Problem encountered: Required Python3 module 'scipy' not found

A full log can be found at /home/csaba/Personal/oversteer/build/meson-logs/meson-log.txt
csaba@csaba-pc:~/Personal/oversteer> meson build
The Meson build system
Version: 0.55.1
Source dir: /home/csaba/Personal/oversteer
Build dir: /home/csaba/Personal/oversteer/build
Build type: native build
Project name: oversteer
Project version: 0.5.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Configuring org.berarma.Oversteer.desktop.tmp using configuration
Program appstream-util found: YES
Program desktop-file-validate found: YES
Configuring oversteer using configuration
Program scripts/meson_post_install.py found: YES (/usr/bin/python3 /home/csaba/Personal/oversteer/scripts/meson_post_install.py)
Build targets in project: 7

Found ninja-1.10.1 at /usr/bin/ninja
csaba@csaba-pc:~/Personal/oversteer> ninja -C build
ninja: Entering directory `build'
[2/2] Generating org.berarma.Oversteer.appdata.xml_data_merge with a custom command
csaba@csaba-pc:~/Personal/oversteer> ninja -C build run
ninja: Entering directory `build'
[0/1] Running external command run
Traceback (most recent call last):
  File "/home/csaba/Personal/oversteer/build/bin/oversteer", line 51, in <module>
    sys.exit(app.run(sys.argv))
  File "/home/csaba/Personal/oversteer/oversteer/application.py", line 70, in run
    model = Model(device)
  File "/home/csaba/Personal/oversteer/oversteer/model.py", line 25, in __init__
    self.read_device_settings()
  File "/home/csaba/Personal/oversteer/oversteer/model.py", line 43, in read_device_settings
    self.flush_device()
  File "/home/csaba/Personal/oversteer/oversteer/model.py", line 57, in flush_device
    self.set_range(data['range'])
  File "/home/csaba/Personal/oversteer/oversteer/model.py", line 125, in set_range
    value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
FAILED: meson-run 
/usr/bin/meson --internal commandrunner /home/csaba/Personal/oversteer /home/csaba/Personal/oversteer/build bin /usr/bin/meson /home/csaba/Personal/oversteer/build/bin/oversteer
ninja: build stopped: subcommand failed.
```

**Comment by berarma** [comment]
Please, pull the branch and try again.

**Comment by patkoscsaba** [comment]
I can confirm the application now starts and detects the wheel. Thanks for the fast and professional response.

**Comment by berarma** [comment]
Thanks.
