### ISSUE TITLE
Clicking "Save As" for a new profile results in error

### ISSUE THREAD

**Issue by patkoscsaba** [berarma/oversteer#34]
Save As button doesn't seem to work. Profiles are not saved.
When I click the button I see this error in the console:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/oversteer/gtk_ui.py", line 484, in on_save_profile_as_clicked
    self.gui.save_profile_as(profile_name)
  File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 252, in save_profile_as
    self.save_profile(profile_file)
  File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 239, in save_profile
    profile.set_ffbmeter_overlay(self.ui.get_ffbmeter_overlay())
  File "/usr/lib/python3.8/site-packages/oversteer/profiles.py", line 69, in set_ffbmeter_overlay
    self.set('ffbmeter_overlay', int(state))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
PS: I am on the gdkfix branch.

**Comment by berarma** [comment]
I'm pushing new fixes to the 0.5.x branch. Can you pull this branch and try it? Thanks,.

It includes the display fix as well.

**Comment by patkoscsaba** [comment]
Saving seems to be working now. Thanks.

**Comment by berarma** [comment]
Thanks for the report and confirmation of the fix!
