### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Kimplul** [berarma/oversteer#41]
Python 3.9 spits out this error when I run Oversteer with the T300RS wheel:

```
Traceback (most recent call last):
  File "/home/kimi/Documents/Projects/oversteer/oversteer/gtk_handlers.py", line 53, in on_device_changed
    self.controller.change_device(device_id)
  File "/home/kimi/Documents/Projects/oversteer/oversteer/gui.py", line 181, in change_device
    self.ui.set_modes(self.model.get_mode_list())
  File "/home/kimi/Documents/Projects/oversteer/oversteer/gtk_ui.py", line 249, in set_modes
    for key, values in enumerate(modes):
TypeError: 'NoneType' object is not iterable
```

This issue seems to have originated in 778d277f5a55badb9b38fd2d5db179fa43621d76.

**Comment by berarma** [comment]
Thanks for the report. Please, check the fix since I don't have a TM wheel to test.

**Comment by Kimplul** [comment]
Works fine with a wheel connected, but if I don't have the wheel plugged in I get this error:
```
Traceback (most recent call last):
  File "/home/kimi/Documents/Projects/oversteer/build/bin/oversteer", line 53, in <module>
    sys.exit(app.run(sys.argv))
  File "/home/kimi/Documents/Projects/oversteer/oversteer/application.py", line 114, in run
    Gui(self, argv)
  File "/home/kimi/Documents/Projects/oversteer/oversteer/gui.py", line 92, in __init__
    self.populate_window()
  File "/home/kimi/Documents/Projects/oversteer/oversteer/gui.py", line 161, in populate_window
    self.populate_devices()
  File "/home/kimi/Documents/Projects/oversteer/oversteer/gui.py", line 151, in populate_devices
    self.model.flush_ui()
  File "/home/kimi/Documents/Projects/oversteer/oversteer/model.py", line 88, in flush_ui
    self.ui.set_mode(data['mode'])
  File "/home/kimi/Documents/Projects/oversteer/oversteer/gtk_ui.py", line 256, in set_mode
    if len(self.emulation_mode_combobox.get_model()) != 0:
TypeError: object of type 'NoneType' has no len()
```
