### ISSUE TITLE
Latest build does not run in Ubuntu 20.04

### ISSUE THREAD

**Issue by sean-skt** [berarma/oversteer#49]
First off, thanks a bunch for this awesome application, love it to bits.
I downloaded and installed the latest build, but unfortunately I get the following errors when trying to run 'oversteer --gui' in Ubuntu 20.04:

Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 53, in <module>
    sys.exit(app.run(sys.argv))
  File "/usr/lib/python3.8/site-packages/oversteer/application.py", line 122, in run
    Gui(self, model, argv)
  File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 66, in __init__
    self.load_preferences()
  File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 254, in load_preferences
    self.button_config[0] = list(map(int, config['DEFAULT']['button_toggle'].split(',')))
  File "/usr/lib/python3.8/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'button_toggle'

Using Logitech G27 with new-lg4ff. A previous build I had installed 9 months ago was working.

EDIT: OK I got it to work by following the suggestion to delete the config.ini file in .config/oversteer.

**Comment by berarma** [comment]
Yes, I have to put a waning before release. This is going to happen to a lot of people, maybe a better error message or some workaround.

Thanks for reporting.
