### ISSUE TITLE
how can i disable gui in order to run the commands at system startup

### ISSUE THREAD

**Issue by siddharthcb** [berarma/oversteer#76]
thanks for the helpful package,
I would like to know if there is a way to run the profile on system startup and when the joystick is detected. 
meanwhile i tried on systemd services to run the commands "sudo oversteer --autocenter 30" and "sudo oversteer --range 360"
but i get the gui error. 

```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(oversteer:6461): Gdk-CRITICAL **: 09:56:23.452: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(oversteer:6460): Gdk-CRITICAL **: 09:56:23.452: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(oversteer:6460): Gdk-CRITICAL **: 09:56:23.573: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(oversteer:6461): Gdk-CRITICAL **: 09:56:23.573: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3.py", line 45, in <module>
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3.py", line 45, in <module>
    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
TypeError: constructor returned NULL
TypeError: constructor returned NULL

During handling of the above exception, another exception occurred:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 51, in <module>
  File "/usr/local/bin/oversteer", line 51, in <module>
    from oversteer.application import Application
    from oversteer.application import Application
  File "/usr/lib/python3.8/site-packages/oversteer/application.py", line 5, in <module>
  File "/usr/lib/python3.8/site-packages/oversteer/application.py", line 5, in <module>
    from oversteer.gui import Gui
    from oversteer.gui import Gui
  File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 20, in <module>
  File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 20, in <module>
    from .combined_chart import CombinedChart
    from .combined_chart import CombinedChart
  File "/usr/lib/python3.8/site-packages/oversteer/combined_chart.py", line 3, in <module>
  File "/usr/lib/python3.8/site-packages/oversteer/combined_chart.py", line 3, in <module>
    from matplotlib.backends.backend_gtk3cairo import FigureCanvasGTK3Cairo as FigureCanvas
    from matplotlib.backends.backend_gtk3cairo import FigureCanvasGTK3Cairo as FigureCanvas
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3cairo.py", line 1, in <module>
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3cairo.py", line 1, in <module>
    from . import backend_cairo, backend_gtk3
    from . import backend_cairo, backend_gtk3
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3.py", line 54, in <module>
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3.py", line 54, in <module>
    raise ImportError(exc)
    raise ImportError(exc)
ImportError: constructor returned NULL
ImportError: constructor returned NULL
```

by the way, i tried solving this by exporting a display but does not work. 

here is my .service file:

```
[Unit]
Description = oversteer
After=local-fs.target

[Service]
Environment=DISPLAY=:0
Environment=XAUTHORITY=/home/ubuntu/.Xauthority
ExecStart=/home/ubuntu/g29_steering_wheel/autostart_scripts/oversteer.sh
Restart=always
RestartSec=10s
StandardOutput=journal+console

[Install]
WantedBy=graphical.target
```

and my oversteer.sh file contains the commands "sudo oversteer --autocenter 30" and "sudo oversteer --range 360"

I have gone through various threads in the forums but none of them seem to work.. 
any insights here would be really helpful

**Comment by berarma** [comment]
I think it's fixed now.

You can change multiple settings in one run:

`oversteer --autocenter 30 --range 360`

Also, you shouldn't need to use sudo.

If you want to setup the wheel when it connects you should run the command or script from udev. You might need a pause to allow the wheel to finish the start sequence before calling Oversteer.

Doing it from systemd might work if the wheel is ready when the service starts.

In case you didn't notice, Oversteer can configure the wheel and start an app or game so you don't need to change configurations manually everytime. It has to be put in the app launcher. It's explained in the README.
