### ISSUE TITLE
Running tests causes ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by greenbigfrog** [berarma/oversteer#77]
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/oversteer/gui.py", line 478, in end_test
    self.linear_chart = LinearChart(self.test.get_input_values(), self.test.get_output_values(),
  File "/usr/lib/python3.9/site-packages/oversteer/linear_chart.py", line 9, in __init__
    self.fposdata = self.output.filter(5)
  File "/usr/lib/python3.9/site-packages/oversteer/signal.py", line 70, in filter
    (times, values) = zip(*self.values)
ValueError: not enough values to unpack (expected 2, got 0)
```
Running tests with my T150 causes the error above.

**Comment by berarma** [comment]
Does the wheel move during the tests? It seems like it's getting no data from the tests.

**Comment by amalon** [comment]
I also see this with T150 on 0.7.0 on archlinux. The wheel moves during the test, but I'm also not seeing any values on the controls tab except hat (even though jstest-gtk shows it just fine.

**Comment by berarma** [comment]
The controls tab won't show wheel rotation when doing tests, I thought it wouldn't be needed. I didn't think too much about it honestly. This is easy to fix.

The test code isn't registering wheel position values during the tests and I don't know why because it's working before and after the tests, doesn't it?

**Comment by amalon** [comment]
@berarma: No, I mean it isn't seeing any values before/after test either. I've hacked around the udev rules apparently not applying (i haven't debugged why yet) with
```
sudo chmod 666 enable_autocenter autocenter gain range
```
yet it clearly is seeing button inputs during the test, but not showing them in gui, nor the values of the axes. Sounds like that is the reason for the test failing.

**Comment by berarma** [comment]
Ah, OK.

Please, try `evtest`. It should show a list of devices including your wheel. Select it and see which events does it generate when acting on it.

**Comment by berarma** [comment]
It's the first time I see those events used in a wheel, despite their name.

ABS_RZ should be the clutch. Don't you have a clutch pedal?

**Comment by amalon** [comment]
Yeh, no clutch pedal unfortunately.

Yes, using scarburato's driver (via AUR). Without the driver oversteer gets the events it expects (though they are muddled up and not in the correct range, e.g. its only in range of steering far to the left of center, and brakes/accel are swapped, and FFB doesn't work when running test, see below).
```
Exception in thread Thread-6 (test1):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/oversteer/test.py", line 129, in test1
    left_effect = self.create_left_effect(0)
  File "/usr/lib/python3.10/site-packages/oversteer/test.py", line 67, in create_left_effect
    left_effect.id = self.input_device.upload_effect(left_effect)
  File "/usr/lib/python3.10/site-packages/evdev/device.py", line 353, in upload_effect
    ff_id = _input.upload_effect(self.fd, data)
OSError: [Errno 38] Function not implemented
```

**Comment by berarma** [comment]
@scarburato, couldn't your driver use the same axes that the device reports? The axes shouldn't change depending on the driver used, or it would be like having a new device with the same identifier. The same for the range of values of each axis.
