### ISSUE TITLE
Error launching oversteer

### ISSUE THREAD

**Issue by SilverLuke** [berarma/oversteer#83]
I get this error when I try to ran the game.
I am using python 3.9.7 on Arch Linux 5.15.2-arch1-1

```
Traceback (most recent call last):
  File "/usr/bin/oversteer", line 51, in <module>
    from oversteer.application import Application
  File "/usr/lib/python3.9/site-packages/oversteer/application.py", line 5, in <module>
    from oversteer.gui import Gui
  File "/usr/lib/python3.9/site-packages/oversteer/gui.py", line 20, in <module>
    from .combined_chart import CombinedChart
  File "/usr/lib/python3.9/site-packages/oversteer/combined_chart.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python3.9/site-packages/matplotlib/pyplot.py", line 36, in <module>
    import matplotlib.colorbar
  File "/usr/lib/python3.9/site-packages/matplotlib/colorbar.py", line 38, in <module>
    from matplotlib import _api, collections, cm, colors, contour, ticker
  File "/usr/lib/python3.9/site-packages/matplotlib/contour.py", line 18, in <module>
    import matplotlib.text as text
  File "/usr/lib/python3.9/site-packages/matplotlib/text.py", line 17, in <module>
    from .textpath import TextPath  # Unused, but imported by others.
  File "/usr/lib/python3.9/site-packages/matplotlib/textpath.py", line 8, in <module>
    from matplotlib import _text_layout, dviread, font_manager, rcParams
  File "/usr/lib/python3.9/site-packages/matplotlib/_text_layout.py", line 10, in <module>
    LayoutItem = dataclasses.make_dataclass(
  File "/usr/lib/python3.9/site-packages/dataclasses.py", line 1132, in make_dataclass
    return dataclass(cls, init=init, repr=repr, eq=eq, order=order,
  File "/usr/lib/python3.9/site-packages/dataclasses.py", line 958, in dataclass
    return wrap(_cls)
  File "/usr/lib/python3.9/site-packages/dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/lib/python3.9/site-packages/dataclasses.py", line 800, in _process_class
    cls_fields = [_get_field(cls, name, type)
  File "/usr/lib/python3.9/site-packages/dataclasses.py", line 800, in <listcomp>
    cls_fields = [_get_field(cls, name, type)
  File "/usr/lib/python3.9/site-packages/dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
  File "/usr/lib/python3.9/site-packages/dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
AttributeError: module 'typing' has no attribute '_ClassVar'
```

**Comment by berarma** [comment]
This looks like some incompatibility in your installed python libs.

A quick Google search has returned these results:
https://github.com/huggingface/transformers/issues/8638
https://github.com/ray-project/tune-sklearn/issues/181

They suggest uninstalling package `dataclasses` or downgrading python to version 3.6.

**Comment by SilverLuke** [comment]
Yes uninstalling `dataclasses` with `pip uninstall dataclasses` make it works now.
Thanks for the fast reply.
