### ISSUE TITLE
Oversteer won't launch on Arch Linux

### ISSUE THREAD

**Issue by lexd0g** [berarma/oversteer#88]
Installed both from AUR and tried compiling/installing manually. Running Python 3.10.1. Here's the error I get when trying to launch, happens both when trying to launch the GUI and trying to run any CLI commands. Also tried installing new-lg4ff.

```
alexandra@bloodstains ~> oversteer
Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 53, in <module>
    sys.exit(app.run(sys.argv))
  File "/usr/lib/python3.10/site-packages/oversteer/application.py", line 127, in run
    from oversteer.gui import Gui
  File "/usr/lib/python3.10/site-packages/oversteer/gui.py", line 24, in <module>
    class Gui:
  File "/usr/lib/python3.10/site-packages/oversteer/gui.py", line 28, in Gui
    _("Press button to set 270°"),
UnicodeDecodeError: 'locale' codec can't decode byte 0xc2 in position 23: decoding error```

**Comment by berarma** [comment]
You should use a locale with UTF-8 support. Is there some reason to use something different?

**Comment by lexd0g** [comment]
I do have UTF-8 locales installed. `en_GB.UTF-8`, `en_US.UTF-8` and `es_ES.UTF-8`.

**Comment by berarma** [comment]
Which one are you using? Please, paste the output of `locale` command.
