### ISSUE TITLE
[Wayland] Oversteer won't launch

### ISSUE THREAD

**Issue by alexbrrsclnt** [berarma/oversteer#94]
Just tried to launch Oversteer in KDE Plasma Wayland session and got this error:

`alex@neon:~
└─ $ oversteer 
Gdk-Message: 11:01:12.390: Unable to load tcross from the cursor theme
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3.py", line 48, in <module>
    cursors.SELECT_REGION : Gdk.Cursor.new(Gdk.CursorType.TCROSS),
TypeError: constructor returned NULL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 53, in <module>
    sys.exit(app.run(sys.argv))
  File "/usr/lib/python3.8/site-packages/oversteer/application.py", line 125, in run
    from oversteer.gui import Gui
  File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 20, in <module>
    from .combined_chart import CombinedChart
  File "/usr/lib/python3.8/site-packages/oversteer/combined_chart.py", line 3, in <module>
    from matplotlib.backends.backend_gtk3cairo import FigureCanvasGTK3Cairo as FigureCanvas
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3cairo.py", line 1, in <module>
    from . import backend_cairo, backend_gtk3
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_gtk3.py", line 54, in <module>
    raise ImportError(exc)
ImportError: constructor returned NULL`

If further testing is need, just tell me!

**Comment by alexbrrsclnt** [comment]
Just some googling and found this
https://github.com/matplotlib/matplotlib/issues/19405
Maybe it can help!

**Comment by berarma** [comment]
Which version of matlib are you using? In Debian/Ubuntu is the `python3-matplotlib` package.

I think you'll need at least 3.4.0 or maybe a newer one.

**Comment by alexbrrsclnt** [comment]
I think that KDE Neon based on Ubuntu 20.04 may be a little bit outdated

```
alex@neon:~
└─ $ dpkg -l  python3-matplotlib
Deseado=desconocido(U)/Instalar/eliminaR/Purgar/retener(H)
| Estado=No/Inst/ficheros-Conf/desempaqUetado/medio-conF/medio-inst(H)/espera-disparo(W)/pendienTe-disparo
|/ Err?=(ninguno)/requiere-Reinst (Estado,Err: mayúsc.=malo)
||/ Nombre             Versión        Arquitectura Descripción
+++-==================-==============-============-====================================================================
ii  python3-matplotlib 3.1.2-1ubuntu4 amd64        Python based plotting system in a style similar to Matlab (Python 3)
```

**Comment by berarma** [comment]
Yes, mixing old with new (Wayland) doesn't always work.

**Comment by berarma** [comment]
Closing as Wayland requires a newer version of Matplotlib.
